source 'http://rubygems.org'

RAILS_VERSION = '~> 3.0.4'
DM_VERSION    = '~> 1.1.0'

# Rails stuff
gem 'rake'
gem 'activesupport',      RAILS_VERSION, :require => 'active_support'
gem 'actionpack',         RAILS_VERSION, :require => 'action_pack'
gem 'actionmailer',       RAILS_VERSION, :require => 'action_mailer'
gem 'railties',           RAILS_VERSION, :require => 'rails'
gem 'jquery-rails'

# Javascript bundling
gem 'apron', :git => 'git://github.com/plusjade/apron.git'

# Datamapper and extensions
gem 'dm-rails',             '~> 1.1.0'
gem 'dm-devise',            '~> 1.2.0'

group(:development) do
  gem 'mongrel', '1.2.0.pre2'
end
